import{a as L,S as w,i as b}from"./assets/vendor-CesYmgD5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();async function y({query:t,page:o}){const r=new URLSearchParams({q:t,key:"19790179-de8e0f050de34d9c55fd8172a",image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15});return(await L.get(`https://pixabay.com/api/?${r}`)).data}const h=document.querySelector(".gallery"),m=document.querySelector(".loader"),g=document.querySelector(".load-more-btn"),v=new w(".gallery a",{captionsData:"alt",captionDelay:250,fadeSpeed:300,overlayOpacity:.9,closeOnOverlayClick:!0,captions:!0});function p(t){const o=t.map(r=>`<li class="gallery-item">
                  <a class="gallery-link" href="${r.largeImageURL}">
                     <img class="gallery-image"
                          src="${r.webformatURL}"
                          alt="${r.tags}"
                          data-source="${r.largeImageURL}"
                          data-tags="${r.tags}" />
                  </a>
                </li>`);h.insertAdjacentHTML("beforeend",o.join("")),v.refresh()}function S(){h.innerHTML=""}function q(){m.classList.add("is-shown")}function O(){m.classList.remove("is-shown")}function R(){g.classList.remove("is-hidden")}function f(){g.classList.add("is-hidden")}const u=document.querySelector(".form"),B=document.querySelector(".load-more-btn");function n(t,o){b.show({color:o,message:t,position:"topRight"})}let i=1,l="",c=0;u.addEventListener("submit",async t=>{t.preventDefault();const r=new FormData(u).get("search-text").trim();if(!(!r||r===l)){l=r,u.reset(),i=1,c=0,S(),f(),q();try{const a=await y({query:l,page:i});if(a.hits.length===0){n("Sorry, there are no images matching your search query. Please try again!","yellow");return}p(a.hits),c+=a.hits.length,i+=1,c>=a.totalHits?(f(),n("We're sorry, but you've reached the end of search results.","yellow")):R()}catch(a){n(a.message,"red")}finally{O()}}});B.addEventListener("click",async()=>{try{const t=await y({query:l,page:i}),{height:o}=document.querySelector(".gallery-item").getBoundingClientRect();p(t.hits),window.scrollBy({top:o*2,behavior:"smooth"}),c+=t.hits.length,i+=1,c>=t.totalHits&&(f(),n("We're sorry, but you've reached the end of search results.","yellow"))}catch(t){n(t.message,"red")}});
//# sourceMappingURL=index.js.map
